uploads = []
generated = []

[[outputs]]
id = "jbph1k-nNUh-59ihjHoFv"
uri = "file://GUIA_PUBLICACAO_STORES.md"
type = "text"
title = "Guia Completo - Publicação nas Stores"

[[outputs]]
id = "ZrOF0q1UhPHjj32ng-1gR"
uri = "file://GUIA_CASA_DOS_20.md"
type = "text"
title = "Guia Completo - Casa dos 20"

[[outputs]]
id = "kT8XlB6Yg6NpSWykm9F2u"
uri = "file://LP_CasaDos20.md"
type = "text"
title = "Documento de Landing Page — Casa dos 20"

[[outputs]]
id = "GUGGPiaiuLLKa25z1CVOu"
uri = "file://INSTRUCOES.md"
type = "text"
title = "Guia de Manutenção — A Casa dos 20"
