export const DAILY_REFLECTIONS = [
  { id: 1, text: "O Senhor é o meu pastor; nada me faltará.", type: "reflection", fromBook: true },
  { id: 2, text: "Busca primeiro o reino de Deus e a Sua justiça, e todas as outras coisas te serão acrescentadas.", type: "reflection", fromBook: true },
  { id: 3, text: "O amor de Deus Pai é incondicional — não depende do que fizeste, mas de quem Ele é.", type: "reflection", fromBook: true },
  { id: 4, text: "Confia no Senhor de todo o teu coração e não te apoies no teu próprio entendimento.", type: "reflection", fromBook: true },
  { id: 5, text: "A Sua graça é suficiente. Nas fraquezas, o poder de Deus se aperfeiçoa.", type: "reflection", fromBook: true },
  { id: 6, text: "Não te deixes vencer pelo mal; antes, vence o mal com o bem.", type: "reflection", fromBook: true },
  { id: 7, text: "Deus Pai conhece os teus planos antes de os formares. Entrega-os a Ele.", type: "reflection", fromBook: true },
  { id: 8, text: "A oração não muda Deus — muda o coração de quem ora.", type: "reflection", fromBook: true },
  { id: 9, text: "O Pai não te pede perfeição — pede um coração disponível e humilde.", type: "reflection", fromBook: true },
  { id: 10, text: "Mesmo na noite mais escura, a presença de Deus Pai permanece.", type: "reflection", fromBook: true },
  { id: 11, text: "Nenhuma lágrima vertida diante do Pai é esquecida por Ele.", type: "reflection", fromBook: true },
  { id: 12, text: "A fé não elimina as dificuldades — garante que não as enfrentas sozinho.", type: "reflection", fromBook: true },
  { id: 13, text: "Ser filho de Deus Pai não é um título — é uma identidade que transforma.", type: "reflection", fromBook: true },
  { id: 14, text: "A misericórdia do Senhor é renovada a cada manhã. Recomeça com Ele.", type: "reflection", fromBook: true },
  { id: 15, text: "Aquele que habita no amor habita em Deus, e Deus habita nele.", type: "reflection", fromBook: true },
  { id: 16, text: "Pede e dar-se-te-á; busca e encontrarás; bate e abrir-se-te-á.", type: "reflection", fromBook: true },
  { id: 17, text: "O Pai vê o que ninguém mais vê — incluindo o teu esforço silencioso.", type: "reflection", fromBook: true },
  { id: 18, text: "A paz de Deus, que excede todo o entendimento, guardará o teu coração.", type: "reflection", fromBook: true },
  { id: 19, text: "Foste criado à imagem de Deus. Isso não muda com as circunstâncias.", type: "reflection", fromBook: true },
  { id: 20, text: "O Senhor está próximo dos que têm o coração quebrantado.", type: "reflection", fromBook: true },
  { id: 21, text: "Com Deus Pai, o que parece impossível tem outro nome: milagre em preparação.", type: "reflection", fromBook: true },
  { id: 22, text: "A adoração não muda as circunstâncias — muda a perspetiva do coração.", type: "reflection", fromBook: true },
  { id: 23, text: "Cada momento de silêncio com o Pai é um momento de encontro real.", type: "reflection", fromBook: true },
  { id: 24, text: "A Sua Palavra é lâmpada para o teu caminho e luz para a tua vereda.", type: "reflection", fromBook: true },
  { id: 25, text: "Deus Pai usa cada estação da vida para te formar à imagem de Cristo.", type: "reflection", fromBook: true },
  { id: 26, text: "O perdão do Pai é mais profundo do que qualquer erro cometido.", type: "reflection", fromBook: true },
  { id: 27, text: "A gratidão abre os olhos para as bênçãos que já existem e que não vemos.", type: "reflection", fromBook: true },
  { id: 28, text: "Não te cansas de procurar a Deus. Ele nunca se cansa de encontrar-te.", type: "reflection", fromBook: true },
  { id: 29, text: "Lança sobre Deus toda a tua ansiedade, porque Ele tem cuidado de ti.", type: "reflection", fromBook: true },
  { id: 30, text: "O tempo de Deus Pai é sempre perfeito, mesmo quando o nosso não o é.", type: "reflection", fromBook: true },
  { id: 31, text: "A tua história está a ser escrita pelo maior Autor que existe.", type: "reflection", fromBook: true },
  { id: 32, text: "Busca o rosto do Pai — não apenas as Suas bênçãos.", type: "reflection", fromBook: true },
  { id: 33, text: "A fidelidade de Deus Pai é maior do que qualquer problema que enfrentas.", type: "reflection", fromBook: true },
  { id: 34, text: "Deus Pai celebra cada passo de fé, por menor que pareça aos teus olhos.", type: "reflection", fromBook: true },
  { id: 35, text: "A esperança no Senhor renova as forças. Aguarda-O e não desanimes.", type: "reflection", fromBook: true },
  { id: 36, text: "Cresce na intimidade com Deus Pai — ela transforma o que nenhuma técnica consegue.", type: "reflection", fromBook: true },
  { id: 37, text: "O amor do Pai por ti existia antes de tu existires.", type: "reflection", fromBook: true },
  { id: 38, text: "A oração é o pulmão da alma. Respira com Deus hoje.", type: "reflection", fromBook: true },
  { id: 39, text: "Confiar em Deus Pai quando não vês o caminho é o maior ato de fé.", type: "reflection", fromBook: true },
  { id: 40, text: "O que o Pai planeou para ti é maior do que o que imaginas para ti mesmo.", type: "reflection", fromBook: true },
  { id: 41, text: "Ser humilde diante do Pai é o início de toda a sabedoria verdadeira.", type: "reflection", fromBook: true },
  { id: 42, text: "A Sua presença é o maior presente que podes receber em qualquer dia.", type: "reflection", fromBook: true },
  { id: 43, text: "Deus Pai nunca desiste de ti — nem nos dias em que desistes de ti mesmo.", type: "reflection", fromBook: true },
  { id: 44, text: "Meditar na Palavra renova a mente e aquieta o coração agitado.", type: "reflection", fromBook: true },
  { id: 45, text: "O teu clamor chega ao coração do Pai antes de sair dos teus lábios.", type: "reflection", fromBook: true },
  { id: 46, text: "Pequenas escolhas de obediência constroem uma vida extraordinária com Deus.", type: "reflection", fromBook: true },
  { id: 47, text: "Nas mãos do Pai, cada desvio se torna um caminho com propósito.", type: "reflection", fromBook: true },
  { id: 48, text: "A solidão pode ser o espaço onde o Pai mais fala. Aprende a escutar.", type: "reflection", fromBook: true },
  { id: 49, text: "O dom da fé cresce cada vez que escolhes confiar apesar do que sentes.", type: "reflection", fromBook: true },
  { id: 50, text: "Nunca estás verdadeiramente sozinho quando o Pai caminha contigo.", type: "reflection", fromBook: true },
  { id: 51, text: "A oração de hoje pode mudar o amanhã de alguém que ainda nem conheces.", type: "reflection", fromBook: true },
  { id: 52, text: "Deus Pai é bom — mesmo quando a vida não parece boa.", type: "reflection", fromBook: true },
  { id: 53, text: "A Sua voz fala em voz baixa. Aprende a reconhecê-la no silêncio.", type: "reflection", fromBook: true },
  { id: 54, text: "Cada versículo memorizado é uma semente plantada para dias difíceis.", type: "reflection", fromBook: true },
  { id: 55, text: "Nada na tua vida passa despercebido ao Pai. Ele é um Deus de detalhes.", type: "reflection", fromBook: true },
  { id: 56, text: "A intimidade com Deus Pai não se constrói nos grandes momentos — constrói-se no diário.", type: "reflection", fromBook: true },
  { id: 57, text: "O amor de Deus Pai é o único amor que nunca falha e nunca se esgota.", type: "reflection", fromBook: true },
  { id: 58, text: "Hoje é um novo encontro com o Pai. Apresenta-te exatamente como és.", type: "reflection", fromBook: true },
  { id: 59, text: "O Pai não precisa das tuas forças — precisa da tua disponibilidade.", type: "reflection", fromBook: true },
  { id: 60, text: "Cada amanhecer é uma nova misericórdia do Pai Celeste. Recebe-a.", type: "reflection", fromBook: true },
  { id: 61, text: "Quando oramos, não mudamos a vontade de Deus — alinhamos a nossa à d'Ele.", type: "reflection", fromBook: true },
  { id: 62, text: "O Pai habita no louvor do Seu povo. A adoração abre o céu.", type: "reflection", fromBook: true },
  { id: 63, text: "A fé sem obras está morta. Deixa que a fé se veja nas tuas escolhas.", type: "reflection", fromBook: true },
  { id: 64, text: "Deus Pai transforma o que é ordinário em extraordinário quando entregamos a Ele.", type: "reflection", fromBook: true },
  { id: 65, text: "O caminho do Pai pode parecer lento, mas nunca chega tarde.", type: "reflection", fromBook: true },
  { id: 66, text: "Cada dificuldade atravessada com fé é um testemunho que ainda hás de contar.", type: "reflection", fromBook: true },
  { id: 67, text: "Honrar a Deus Pai no pequeno é o treino para o maior.", type: "reflection", fromBook: true },
  { id: 68, text: "O Pai quer comunhão contigo — não apenas a tua obediência.", type: "reflection", fromBook: true },
  { id: 69, text: "Deixa que a paz de Cristo seja o árbitro do teu coração hoje.", type: "reflection", fromBook: true },
  { id: 70, text: "A presença de Deus Pai transforma o comum em sagrado.", type: "reflection", fromBook: true },
  { id: 71, text: "Um coração grato é um coração que reconhece Deus em cada pormenor.", type: "reflection", fromBook: true },
  { id: 72, text: "O Pai conhece o teu nome. Para Ele, não és apenas mais um.", type: "reflection", fromBook: true },
  { id: 73, text: "A esperança em Deus Pai nunca envergonha — ela transforma.", type: "reflection", fromBook: true },
  { id: 74, text: "Amar o próximo é um ato de adoração a Deus Pai.", type: "reflection", fromBook: true },
  { id: 75, text: "O Pai planeou o teu propósito antes de te criar. Busca-O para descobrires.", type: "reflection", fromBook: true },
  { id: 76, text: "Cada dom que tens foi dado pelo Pai para servir e amar o próximo.", type: "reflection", fromBook: true },
  { id: 77, text: "Ser transformado à imagem de Cristo é o maior crescimento possível.", type: "reflection", fromBook: true },
  { id: 78, text: "O Pai é o mesmo ontem, hoje e para sempre. Descansa nessa certeza.", type: "reflection", fromBook: true },
  { id: 79, text: "A obediência ao Pai não é prisão — é o caminho para a verdadeira liberdade.", type: "reflection", fromBook: true },
  { id: 80, text: "Não precisas de ter tudo resolvido para orar. Ora com o que tens agora.", type: "reflection", fromBook: true },
  { id: 81, text: "O amor do Pai cobre uma multidão de falhas — inclusive as tuas.", type: "reflection", fromBook: true },
  { id: 82, text: "A fé é a certeza das coisas que se esperam e a convicção das que não se veem.", type: "reflection", fromBook: true },
  { id: 83, text: "O que plantas em oração, colhes em fé no tempo do Pai.", type: "reflection", fromBook: true },
  { id: 84, text: "Deus Pai usa as pessoas imperfeitas — é por isso que te pode usar a ti.", type: "reflection", fromBook: true },
  { id: 85, text: "A Sua bondade persegue-te todos os dias da tua vida.", type: "reflection", fromBook: true },
  { id: 86, text: "Quando buscas o Pai de todo o coração, encontras-O.", type: "reflection", fromBook: true },
  { id: 87, text: "A Palavra de Deus não volta vazia — faz o que Ele propôs.", type: "reflection", fromBook: true },
  { id: 88, text: "Hoje, leva a presença de Deus Pai para cada conversa e decisão.", type: "reflection", fromBook: true },
  { id: 89, text: "A tua identidade está em Cristo — não nas circunstâncias nem nas opiniões.", type: "reflection", fromBook: true },
  { id: 90, text: "O Pai está mais interessado no teu caráter do que no teu conforto.", type: "reflection", fromBook: true },
  { id: 91, text: "Cada 'sim' ao Pai é um passo em direção ao melhor que Ele preparou.", type: "reflection", fromBook: true },
  { id: 92, text: "A humildade não é pensar menos de ti — é pensar menos em ti e mais no Pai.", type: "reflection", fromBook: true },
  { id: 93, text: "Deus Pai é o único que consegue fazer de cada fraqueza uma fortaleza.", type: "reflection", fromBook: true },
  { id: 94, text: "Não temas, porque Deus Pai está contigo. Não desanimes, porque Ele é o teu Deus.", type: "reflection", fromBook: true },
  { id: 95, text: "A tua oração mais simples e honesta é mais poderosa do que pensas.", type: "reflection", fromBook: true },
  { id: 96, text: "O Pai está a completar a boa obra que começou em ti. Confia no processo.", type: "reflection", fromBook: true },
  { id: 97, text: "Renderes-te ao amor do Pai não é fraqueza — é a decisão mais sábia que podes tomar.", type: "reflection", fromBook: true },
  { id: 98, text: "Quando buscas o Pai em primeiro lugar, tudo o mais encontra o seu lugar.", type: "reflection", fromBook: true },
  { id: 99, text: "Cada encontro com Deus Pai deixa uma marca que o mundo não consegue apagar.", type: "reflection", fromBook: true },
  { id: 100, text: "Hoje, escolhe deliberadamente a presença de Deus Pai sobre o ruído do mundo.", type: "reflection", fromBook: true },
];
