export const JOURNEY_TITLES: Record<string, { title: string; days: { id: string; day: number; title: string; description: string }[] }> = {
  "autoconhecimento": {
    title: "Quem Sou Eu?",
    days: [
      { id: "auto-1", day: 1, title: "O Piloto Automático", description: "Liste 5 coisas que você faz todo dia sem pensar. Para cada uma: é uma escolha sua ou um hábito herdado?" },
      { id: "auto-2", day: 2, title: "Quem Sou Sem Instagram?", description: "Se as redes sociais acabassem amanhã, o que sobraria da sua identidade? Escreva sem censura." },
      { id: "auto-3", day: 3, title: "Exercício do Espelho", description: "Olhe no espelho por 3 minutos em silêncio. Sem celular. O que você sente? O que aparece?" },
      { id: "auto-4", day: 4, title: "Vá às Perguntas", description: "Abra as Perguntas no app, tema Identidade. Responda 3 perguntas no seu diário." },
      { id: "auto-5", day: 5, title: "A Máscara Social", description: "Qual versão de você aparece no trabalho? E com amigos? E com família? São todas você?" },
      { id: "auto-6", day: 6, title: "Carta à Criança Interior", description: "Escreva uma carta para o seu eu de 10 anos. O que diria? O que aquela criança precisa ouvir?" },
      { id: "auto-7", day: 7, title: "Um Dia Sem Personagem", description: "Hoje, em pelo menos uma conversa, diga exatamente o que sente. Sem filtrar." },
      { id: "auto-8", day: 8, title: "Valores vs. Realidade", description: "Liste seus 5 maiores valores. Agora olhe sua última semana: você viveu de acordo com eles?" },
      { id: "auto-9", day: 9, title: "Rótulos que Carrego", description: "Liste todos os rótulos que te deram: 'responsável', 'engraçado', 'forte'. Quais são seus e quais são dos outros?" },
      { id: "auto-10", day: 10, title: "Registre no Diário", description: "Abra o Diário no app. Escreva: 'Hoje descobri sobre mim que...' Complete com honestidade." },
      { id: "auto-11", day: 11, title: "O Que Me Irrita?", description: "O que mais te irrita nos outros? Reflexão: alguma dessas coisas existe em você? (Spoiler: provavelmente sim.)" },
      { id: "auto-12", day: 12, title: "Corpo e Mente", description: "Onde seu corpo guarda tensão? Ombros? Mandíbula? Faça um scan de 5 minutos deitado." },
      { id: "auto-13", day: 13, title: "Autossabotagem Real", description: "Em que áreas você se sabota? Procrastinar coisas importantes, fugir de conversas, comparação... Seja honesto." },
      { id: "auto-14", day: 14, title: "Checkpoint: Semana 2", description: "Releia tudo que escreveu até aqui. O que te surpreendeu? Abra o Diário e registre seus insights." },
      { id: "auto-15", day: 15, title: "Dizer Não Sem Culpa", description: "Diga 'não' para algo hoje. Sem desculpa, sem justificativa excessiva. Apenas: 'não consigo agora'." },
      { id: "auto-16", day: 16, title: "Meus Medos Reais", description: "Liste seus 5 maiores medos. Não os genéricos — os reais. Medo de fracassar em quê? Medo de perder quem?" },
      { id: "auto-17", day: 17, title: "Energia +/-", description: "Liste 5 coisas que te dão energia e 5 que drenam. Quanto tempo você gasta em cada grupo?" },
      { id: "auto-18", day: 18, title: "Responda no App", description: "Vá às Perguntas, tema Identidade. Escolha a pergunta que mais te assusta e responda no Diário." },
      { id: "auto-19", day: 19, title: "Desconectar 3 Horas", description: "Fique 3 horas sem redes sociais. Sem stories, sem scroll. Registre como se sentiu depois." },
      { id: "auto-20", day: 20, title: "O Que Finjo Não Sentir", description: "Que emoção você mais reprime? Raiva? Tristeza? Medo? Por quê?" },
      { id: "auto-21", day: 21, title: "Vulnerabilidade Real", description: "Compartilhe algo vulnerável com alguém de confiança hoje. Algo que normalmente esconderia." },
      { id: "auto-22", day: 22, title: "Perdão Necessário", description: "Escreva uma carta de perdão — para alguém ou para si mesmo. Não precisa enviar. Precisa sentir." },
      { id: "auto-23", day: 23, title: "Silêncio de 15 Minutos", description: "Sente sem fazer nada. Sem celular, sem música. 15 minutos. Observe o que surge na mente." },
      { id: "auto-24", day: 24, title: "Minha Contradição", description: "Qual é sua maior contradição? (Ex: 'Quero conexão mas me afasto.' 'Quero mudar mas tenho medo.')" },
      { id: "auto-25", day: 25, title: "Registre Sua Evolução", description: "Abra o Diário. Escreva sobre quem você era no dia 1 e quem está se tornando." },
      { id: "auto-26", day: 26, title: "Conversa Adiada", description: "Tenha aquela conversa que você vem adiando. Não precisa ser perfeita — precisa ser real." },
      { id: "auto-27", day: 27, title: "Meu Legado", description: "Se morresse amanhã, pelo que gostaria de ser lembrado? Isso está alinhado com como vive hoje?" },
      { id: "auto-28", day: 28, title: "Ritual Pessoal", description: "Crie um ritual diário de 5 minutos que represente quem você quer ser. Comece hoje." },
      { id: "auto-29", day: 29, title: "Reflexão Final", description: "Vá às Perguntas, tema Identidade. Responda: 'Você se conhece ou apenas se acostumou consigo mesmo?'" },
      { id: "auto-30", day: 30, title: "Carta ao Eu Futuro", description: "Escreva uma carta para o seu eu daqui a 1 ano. Guarde no Diário. Releia quando a hora chegar." },
    ],
  },
  "detox-digital": {
    title: "Detox Digital",
    days: [
      { id: "detox-1", day: 1, title: "Diagnóstico Brutal", description: "Veja seu tempo de tela de ontem. Quantas horas? Em quais apps? Escreva o número sem julgamento." },
      { id: "detox-2", day: 2, title: "Primeira Hora Sagrada", description: "Hoje: não pegue o celular na primeira hora após acordar. Faça qualquer outra coisa." },
      { id: "detox-3", day: 3, title: "Notificações Off", description: "Desative TODAS as notificações de redes sociais. Só deixe ligado: ligações e mensagens reais." },
      { id: "detox-4", day: 4, title: "Diário da Ansiedade Digital", description: "Toda vez que pegar o celular sem motivo hoje, anote: que hora, o que sentia, o que fez." },
      { id: "detox-5", day: 5, title: "Reflita no App", description: "Vá às Perguntas, tema Identidade. Responda: 'Qual é a diferença entre o que você mostra no Instagram e quem você é de verdade?'" },
      { id: "detox-6", day: 6, title: "Refeição Sem Tela", description: "Faça todas as refeições de hoje sem celular na mesa. Sem YouTube, sem scroll. Sinta a comida." },
      { id: "detox-7", day: 7, title: "Caminhada Analógica", description: "Saia para uma caminhada de 20 minutos sem fone e sem celular (ou no bolso, modo avião)." },
      { id: "detox-8", day: 8, title: "Por Que Eu Scrolo?", description: "Reflexão honesta: o que você busca no scroll infinito? Validação? Distração? Fuga de quê?" },
      { id: "detox-9", day: 9, title: "Unfollow Massivo", description: "Deixe de seguir pelo menos 20 perfis que não agregam nada real à sua vida. Sem culpa." },
      { id: "detox-10", day: 10, title: "3 Horas Sem Redes", description: "Escolha um período de 3 horas hoje para ficar completamente sem redes sociais." },
      { id: "detox-11", day: 11, title: "Registre no Diário", description: "Abra o Diário. Escreva: 'O que eu faria com 3 horas extras por dia?' (Esse é seu tempo de tela.)" },
      { id: "detox-12", day: 12, title: "Comparação é Veneno", description: "Liste 3 vezes que se comparou com alguém nas redes esta semana. O que sentiu? Era real?" },
      { id: "detox-13", day: 13, title: "Modo Avião à Noite", description: "A partir de hoje, celular em modo avião 1 hora antes de dormir. Use um despertador real." },
      { id: "detox-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Compare seu tempo de tela com o dia 1. Melhorou? O que mudou na sua rotina e humor?" },
      { id: "detox-15", day: 15, title: "Presença Total", description: "No próximo encontro social, guarde o celular. 100% presente. Observe como as pessoas reagem." },
      { id: "detox-16", day: 16, title: "Hobby Analógico", description: "Dedique 30 minutos a algo que não envolva tela: desenhar, cozinhar, ler físico, instrumento." },
      { id: "detox-17", day: 17, title: "Dopamina Real", description: "O scroll libera dopamina barata. Liste 5 coisas que te dão dopamina real: exercício, conquista, conexão..." },
      { id: "detox-18", day: 18, title: "Diário de Gratidão Offline", description: "Escreva 5 coisas boas do seu dia que não precisaram de internet para existir." },
      { id: "detox-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Solidão. A solidão que você sente é real ou é solidão digital?" },
      { id: "detox-20", day: 20, title: "Dia Inteiro Sem Stories", description: "Não poste e não veja stories por 24 horas. O mundo continua girando." },
      { id: "detox-21", day: 21, title: "Tédio Produtivo", description: "Quando sentir tédio hoje, NÃO pegue o celular. Fique entediado. Observe o que surge." },
      { id: "detox-22", day: 22, title: "Relações Reais vs. Digitais", description: "Quantas conversas significativas você teve esta semana? Presenciais vs. online?" },
      { id: "detox-23", day: 23, title: "Meditação Sem Guia", description: "Medite 10 minutos sem app de meditação. Só você, silêncio e respiração." },
      { id: "detox-24", day: 24, title: "Limpar o Feed", description: "Curadoria radical: deixe apenas conteúdos que te fazem pensar, crescer ou rir de verdade." },
      { id: "detox-25", day: 25, title: "Registre Sua Evolução", description: "Abra o Diário. Como sua relação com o celular mudou? O que conquistou? O que ainda é difícil?" },
      { id: "detox-26", day: 26, title: "Conversa Face a Face", description: "Ligue ou encontre alguém pessoalmente. Nada de mensagem de texto. Voz ou presença." },
      { id: "detox-27", day: 27, title: "Manhã Completa Offline", description: "Das 7h ao meio-dia sem redes sociais. Apenas trabalho/estudo e vida real." },
      { id: "detox-28", day: 28, title: "Identidade Além da Tela", description: "Se suas redes sociais sumissem hoje, quem você seria? Escreva sem pressa." },
      { id: "detox-29", day: 29, title: "Regras Pessoais", description: "Crie 5 regras pessoais para o uso de celular que vai seguir daqui pra frente. Assine." },
      { id: "detox-30", day: 30, title: "Compare e Celebre", description: "Veja seu tempo de tela. Compare com o dia 1. Abra o Diário e celebre sua evolução." },
    ],
  },
  "proposito-profissional": {
    title: "E Agora, Profissão?",
    days: [
      { id: "prof-1", day: 1, title: "Pressão Silenciosa", description: "De onde vem a pressão de 'saber o que fazer'? Família? Amigos? Redes sociais? Escreva honestamente." },
      { id: "prof-2", day: 2, title: "O Que Me Faz Perder a Hora", description: "Liste 5 atividades que te fazem perder a noção do tempo. Sem pensar em dinheiro ou prestígio." },
      { id: "prof-3", day: 3, title: "Reflita no App", description: "Vá às Perguntas, tema Propósito. Responda 3 perguntas que te chamem atenção no seu Diário." },
      { id: "prof-4", day: 4, title: "Sucesso Redefinido", description: "Escreva SUA definição de sucesso. Não a dos seus pais, nem a do LinkedIn. A SUA." },
      { id: "prof-5", day: 5, title: "Conversas que Abrem Portas", description: "Mande mensagem para alguém que trabalha com algo que te interessa. Pergunte como é a rotina real." },
      { id: "prof-6", day: 6, title: "Habilidades Escondidas", description: "Liste tudo que você sabe fazer — até coisas 'bobas'. Cozinhar, organizar, ouvir, criar memes. Tudo conta." },
      { id: "prof-7", day: 7, title: "Um Dia de Experiência", description: "Faça algo que nunca fez por 30 minutos: programe, cozinhe algo novo, desenhe, grave um vídeo." },
      { id: "prof-8", day: 8, title: "Ikigai Pessoal", description: "Desenhe: O que amo + O que faço bem + O que o mundo precisa + O que posso ser pago. Onde se cruzam?" },
      { id: "prof-9", day: 9, title: "Medo do Fracasso", description: "O que exatamente você teme quando pensa em 'não dar certo'? Detalhe. O medo perde poder quando nomeado." },
      { id: "prof-10", day: 10, title: "Registre no Diário", description: "Abra o Diário. Escreva: 'Se dinheiro não fosse problema, eu estaria...' Complete sem censura." },
      { id: "prof-11", day: 11, title: "Mentores Invisíveis", description: "Quem te inspira? 3 pessoas reais (não celebridades). O que cada uma te ensina sobre viver/trabalhar?" },
      { id: "prof-12", day: 12, title: "Propósito ≠ Profissão", description: "Seu propósito não precisa ser seu emprego. Reflita: o que você faria de graça? O que faz por obrigação?" },
      { id: "prof-13", day: 13, title: "Teste de 1 Hora", description: "Escolha algo que te interessa e dedique 1 hora aprendendo online. Gostou? Sentiria tesão de continuar?" },
      { id: "prof-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Releia tudo que escreveu. Algum padrão apareceu? O que te surpreendeu? Registre no Diário." },
      { id: "prof-15", day: 15, title: "Carta ao LinkedIn", description: "Se pudesse escrever o que quiser na bio do LinkedIn sem medo de julgamento, o que colocaria?" },
      { id: "prof-16", day: 16, title: "5 Vidas Possíveis", description: "Se pudesse viver 5 vidas paralelas, qual profissão teria em cada uma? Liste sem filtro." },
      { id: "prof-17", day: 17, title: "Conversa Real", description: "Pergunte a 3 pessoas diferentes: 'O que você acha que eu faria bem?' Anote sem contestar." },
      { id: "prof-18", day: 18, title: "Micro-Experimento", description: "Escolha 1 das suas '5 vidas' do dia 16. Faça algo concreto hoje relacionado: pesquise, teste, crie." },
      { id: "prof-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Propósito. Responda: 'O que te faz levantar da cama todos os dias?'" },
      { id: "prof-20", day: 20, title: "Eliminação por Experiência", description: "Liste 3 coisas que você SABE que não quer fazer. Eliminar opções também é avanço." },
      { id: "prof-21", day: 21, title: "Projeto-Semente", description: "Pense num mini-projeto pessoal que te anime. Blog, canal, produto, serviço. Dê o primeiro micro-passo." },
      { id: "prof-22", day: 22, title: "Impacto que Quero Causar", description: "Se pudesse resolver 1 problema do mundo, qual seria? Isso pode ser pista do seu caminho." },
      { id: "prof-23", day: 23, title: "Meditação de Intenção", description: "10 minutos em silêncio com 1 pergunta: 'O que meu coração quer que eu faça?' Não force a resposta." },
      { id: "prof-24", day: 24, title: "Currículo de Vida", description: "Escreva um currículo, mas com experiências de VIDA, não de trabalho. Viagens, superações, amizades." },
      { id: "prof-25", day: 25, title: "Registre no Diário", description: "Abra o Diário. Escreva: 'Daqui a 5 anos, quero que minha vida seja assim...' Detalhe." },
      { id: "prof-26", day: 26, title: "Sair da Teoria", description: "Pare de pesquisar e FAÇA algo hoje. Qualquer ação concreta, mesmo pequena, vale mais que 100 planos." },
      { id: "prof-27", day: 27, title: "Aceitar o Não-Saber", description: "Tá tudo bem não saber ainda. Escreva: 'Eu me permito não ter todas as respostas agora.'" },
      { id: "prof-28", day: 28, title: "Rede de Apoio", description: "Conte para alguém de confiança sobre algo que descobriu nessa jornada. Verbalizar solidifica." },
      { id: "prof-29", day: 29, title: "Manifesto Pessoal", description: "Escreva um manifesto de 10 frases sobre o que você defende, acredita e quer para sua vida." },
      { id: "prof-30", day: 30, title: "1 Compromisso Real", description: "Escolha 1 ação concreta para os próximos 30 dias. Não precisa ser 'a resposta' — precisa ser um passo." },
    ],
  },
  "conexao": {
    title: "Conexão de Verdade",
    days: [
      { id: "con-1", day: 1, title: "Mapa de Relações", description: "Desenhe 3 círculos: íntimos (ligaria às 3h), amigos, conhecidos. Quantas pessoas em cada?" },
      { id: "con-2", day: 2, title: "Escuta Radical", description: "Na próxima conversa, apenas ouça. Sem interromper, sem preparar resposta, sem olhar o celular. Só ouvir." },
      { id: "con-3", day: 3, title: "Mensagem Inesperada", description: "Mande uma mensagem sincera para alguém que não espera. 'Lembrei de você. Tá tudo bem?'" },
      { id: "con-4", day: 4, title: "Reflita no App", description: "Vá às Perguntas, tema Relações. Responda 3 perguntas no seu Diário." },
      { id: "con-5", day: 5, title: "Linguagem do Amor", description: "Qual é a sua? (Palavras, toque, tempo, presentes, atos?) E das 3 pessoas mais próximas?" },
      { id: "con-6", day: 6, title: "Presença > Presentes", description: "No próximo encontro, guarde o celular no bolso. Esteja 100% ali. Observe a diferença." },
      { id: "con-7", day: 7, title: "Agradecimento Real", description: "Agradeça 3 pessoas hoje — pessoalmente ou por mensagem. Seja específico sobre o PORQUÊ." },
      { id: "con-8", day: 8, title: "Conflito ≠ Fim", description: "Como você lida com conflitos? Foge? Ataca? Engole? Escreva seu padrão com honestidade." },
      { id: "con-9", day: 9, title: "Vulnerabilidade Corajosa", description: "Compartilhe algo vulnerável com alguém de confiança. Algo que normalmente esconderia." },
      { id: "con-10", day: 10, title: "Registre no Diário", description: "Abra o Diário. Escreva sobre a relação que mais te importa e o que ela precisa de você." },
      { id: "con-11", day: 11, title: "Perdão em Andamento", description: "Há alguém que você precisa perdoar? Escreva o que sente. Não precisa enviar, precisa processar." },
      { id: "con-12", day: 12, title: "Elogio Genuíno", description: "Elogie 3 pessoas hoje de forma específica. Não 'você é legal' — 'admiro como você lida com...'" },
      { id: "con-13", day: 13, title: "Encontro Real", description: "Marque um encontro presencial com alguém que só fala por mensagem. Café, caminhada, qualquer coisa." },
      { id: "con-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Como suas relações mudaram? Registre seus insights no Diário." },
      { id: "con-15", day: 15, title: "Limites Com Amor", description: "Em qual relação você precisa de um limite? Escreva o que diria. Se tiver coragem, diga." },
      { id: "con-16", day: 16, title: "Herança Emocional", description: "Que padrões de relacionamento você herdou da família? Quais quer manter e quais quer mudar?" },
      { id: "con-17", day: 17, title: "Pedido de Desculpas", description: "Peça desculpas a alguém, mesmo por algo pequeno. Humildade genuína conecta mais que qualquer palavrão bonito." },
      { id: "con-18", day: 18, title: "Silêncio Compartilhado", description: "Fique em silêncio com alguém por 5 minutos. Sem celular. Apenas presença. Observe o que sente." },
      { id: "con-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Relações. 'Quantas das suas amizades sobreviveriam sem Internet?' Reflita no Diário." },
      { id: "con-20", day: 20, title: "Generosidade Silenciosa", description: "Faça algo generoso sem contar para ninguém. Pague um café, ajude um estranho, doe algo." },
      { id: "con-21", day: 21, title: "Dependência vs. Parceria", description: "Em qual relação você depende demais? Em qual é parceiro? A diferença importa." },
      { id: "con-22", day: 22, title: "Carta ao Amigo Distante", description: "Escreva para alguém que se afastou. Pode ser no Diário. Se quiser, mande de verdade." },
      { id: "con-23", day: 23, title: "Comunicação Não-Violenta", description: "Pratique: Observação + Sentimento + Necessidade + Pedido. Use em uma conversa real hoje." },
      { id: "con-24", day: 24, title: "Humor Conecta", description: "Faça alguém rir hoje genuinamente. O humor é uma das formas mais poderosas de conexão." },
      { id: "con-25", day: 25, title: "Registre no Diário", description: "Abra o Diário. 'O que eu trago de bom para as pessoas ao meu redor?' Escreva com honestidade." },
      { id: "con-26", day: 26, title: "Dia de Sim", description: "Aceite um convite social que normalmente recusaria. Saia da caverna." },
      { id: "con-27", day: 27, title: "Qualidade > Quantidade", description: "Não precisa de 50 amigos. Precisa de 3 reais. Quem são os seus? Você nutre essas relações?" },
      { id: "con-28", day: 28, title: "Amor-Bondade", description: "Medite 10 min desejando felicidade: para si, para alguém amado, para alguém difícil, para todos." },
      { id: "con-29", day: 29, title: "O Que Eu Ofereço", description: "O que você traz para seus relacionamentos? E o que espera receber? Está equilibrado?" },
      { id: "con-30", day: 30, title: "1 Gesto Concreto", description: "Escolha 1 relação para nutrir ativamente. Faça o primeiro gesto agora. Ligue, visite, escreva." },
    ],
  },
  "ansiedade": {
    title: "Cala a Boca, Ansiedade",
    days: [
      { id: "ans-1", day: 1, title: "Mapa da Ansiedade", description: "Liste 5 coisas que te causam ansiedade hoje. Para cada uma: é algo que você pode controlar?" },
      { id: "ans-2", day: 2, title: "Respiração 4-7-8", description: "Quando a ansiedade vier: inspire 4s, segure 7s, expire 8s. Faça 5 rodadas agora. Decore esse exercício." },
      { id: "ans-3", day: 3, title: "Diário da Ansiedade", description: "Toda vez que sentir ansiedade hoje, anote: o gatilho, a sensação no corpo, quanto durou." },
      { id: "ans-4", day: 4, title: "Reflita no App", description: "Vá às Perguntas, tema Incerteza. Responda 3 perguntas no Diário." },
      { id: "ans-5", day: 5, title: "O Pior Cenário", description: "Escreva seu pior cenário para algo que te preocupa. Depois: 'Se acontecesse, eu sobreviveria?' Quase sempre: sim." },
      { id: "ans-6", day: 6, title: "Grounding 5-4-3-2-1", description: "Quando ansioso: 5 coisas que vê, 4 que ouve, 3 que toca, 2 que cheira, 1 que prova. Volta pro presente." },
      { id: "ans-7", day: 7, title: "Movimento Anti-Ansiedade", description: "Quando a ansiedade apertar: 20 agachamentos, 20 polichinelos, 10 flexões. O corpo resolve o que a mente não consegue." },
      { id: "ans-8", day: 8, title: "Comparação é Ansiedade", description: "Quantas vezes hoje você se comparou com alguém? Em quê? A comparação alimenta a ansiedade — perceba." },
      { id: "ans-9", day: 9, title: "Decisão Imperfeita", description: "Tome uma decisão que tem adiado. Qualquer uma. A perfeição paralisa — ação imperfeita liberta." },
      { id: "ans-10", day: 10, title: "Registre no Diário", description: "Abra o Diário. 'O que minha ansiedade está tentando me dizer?' Às vezes ela é um aviso, não um inimigo." },
      { id: "ans-11", day: 11, title: "Futuro vs. Presente", description: "Quantos dos seus problemas atuais são REAIS agora vs. 'e se acontecer'? Liste e separe." },
      { id: "ans-12", day: 12, title: "Noite Sem Tela", description: "1 hora antes de dormir: sem celular. Leia, tome chá, converse. A noite dita o sono — o sono dita a ansiedade." },
      { id: "ans-13", day: 13, title: "Conversa com o Medo", description: "Escreva um diálogo entre você e sua ansiedade. O que ela diria? E o que você responderia?" },
      { id: "ans-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Compare sua ansiedade com o dia 1 (0-10). O que ajudou? Registre no Diário." },
      { id: "ans-15", day: 15, title: "Planejamento Flexível", description: "Planeje algo com 3 cenários: ideal, aceitável, plano B. A rigidez alimenta a ansiedade." },
      { id: "ans-16", day: 16, title: "Pedir Ajuda", description: "Peça ajuda para algo hoje. A vulnerabilidade de pedir reduz a ansiedade de ter que dar conta sozinho." },
      { id: "ans-17", day: 17, title: "Caminhar é Meditar", description: "Caminhada de 20 minutos focando nos passos. Cada passo = um pensamento que vai embora." },
      { id: "ans-18", day: 18, title: "Gratidão pelo Presente", description: "Liste 5 coisas que estão BEM agora. A ansiedade te faz esquecer o que já funciona." },
      { id: "ans-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Incerteza. 'Você controla ou é controlado(a) pelos seus medos?'" },
      { id: "ans-20", day: 20, title: "Erro Intencional", description: "Erre de propósito em algo pequeno. Quebre a louça da perfeição. O mundo não acaba." },
      { id: "ans-21", day: 21, title: "Rotina de Âncora", description: "Crie 1 ritual matinal de 5 minutos. Sempre igual. Previsibilidade reduz ansiedade." },
      { id: "ans-22", day: 22, title: "Cafeína e Ansiedade", description: "Reduza cafeína pela metade hoje. Observe se há diferença no nível de ansiedade." },
      { id: "ans-23", day: 23, title: "Meditação do Barco", description: "Visualize-se num barco em um rio calmo. A corrente te leva. Solte os remos. 10 minutos." },
      { id: "ans-24", day: 24, title: "Luto do Controle", description: "Escreva: 'Eu solto o controle sobre ___.' Complete com aquilo que você precisa soltar." },
      { id: "ans-25", day: 25, title: "Registre no Diário", description: "Abra o Diário. O que sua ansiedade te protege de fazer? O que você faria se ela calasse?" },
      { id: "ans-26", day: 26, title: "Micro-Coragem", description: "Faça 3 coisas que te dão um leve desconforto hoje. Não 50% fora do conforto — apenas 5%." },
      { id: "ans-27", day: 27, title: "Reescreva a Narrativa", description: "Substitua 'E se der errado?' por 'E se der certo?' em 3 situações da sua semana." },
      { id: "ans-28", day: 28, title: "Confiar no Processo", description: "Escreva: 'Eu confio que ___.' Complete com o que precisa acreditar agora." },
      { id: "ans-29", day: 29, title: "Kit Anti-Ansiedade", description: "Monte seu kit pessoal: 3 exercícios de respiração, 3 ações físicas, 3 frases que te acalmam." },
      { id: "ans-30", day: 30, title: "Mantra do Navegante", description: "Crie seu mantra pessoal para momentos de ansiedade. Memorize. Registre no Diário como encerramento." },
    ],
  },
  "crescimento": {
    title: "Sair da Estagnação",
    days: [
      { id: "cresc-1", day: 1, title: "Raio-X da Vida", description: "Nota de 1-10 para: Saúde, Relações, Propósito, Mente, Diversão. Onde está a urgência?" },
      { id: "cresc-2", day: 2, title: "1 Micro-Hábito", description: "Escolha 1 hábito absurdamente pequeno: 1 copo d'água, 5 min de leitura, 10 flexões. Comece HOJE." },
      { id: "cresc-3", day: 3, title: "Zona de Expansão", description: "Faça algo 5% fora do seu conforto. Não 50%. Crescimento é gradual, não trauma." },
      { id: "cresc-4", day: 4, title: "Reflita no App", description: "Vá às Perguntas, tema Crescimento. Responda 3 perguntas que te desafiem." },
      { id: "cresc-5", day: 5, title: "Vitórias Ignoradas", description: "Liste 5 pequenas vitórias recentes que você não celebrou. Reconhecer progresso gera mais progresso." },
      { id: "cresc-6", day: 6, title: "Feedback Corajoso", description: "Peça feedback honesto a alguém: 'O que posso melhorar?' Ouça sem se defender. Agradeça." },
      { id: "cresc-7", day: 7, title: "Eliminar 1 Hábito", description: "Identifique 1 hábito que não te serve. (Scroll antes de dormir? Procrastinar? Junk food?) Comece a substituir." },
      { id: "cresc-8", day: 8, title: "30 Min de Movimento", description: "Dança, corrida, yoga, academia, caminhada rápida. 30 minutos de movimento intencional." },
      { id: "cresc-9", day: 9, title: "Aprender Algo Novo", description: "20 minutos aprendendo algo totalmente novo: idioma, instrumento, skill digital, receita." },
      { id: "cresc-10", day: 10, title: "Registre no Diário", description: "Abra o Diário. 'O que me impede de ser a pessoa que admiro?' Escreva com honestidade brutal." },
      { id: "cresc-11", day: 11, title: "Crenças Limitantes", description: "'Não sou bom o suficiente.' 'Não mereço.' 'Não tenho talento.' Qual crença te trava? Desafie-a." },
      { id: "cresc-12", day: 12, title: "Dieta de Informação", description: "Consuma apenas conteúdo intencional hoje. Zero scroll automático. Você escolhe o que entra." },
      { id: "cresc-13", day: 13, title: "Foco Total", description: "1 hora de trabalho/estudo sem NENHUMA distração. Modo avião. Timer ligado. Observe o poder." },
      { id: "cresc-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Reveja suas notas do dia 1. Algo mudou? Registre no Diário." },
      { id: "cresc-15", day: 15, title: "Fracasso = Informação", description: "Relembre um fracasso. Extraia 3 aprendizados concretos. O fracasso é dado, não veredicto." },
      { id: "cresc-16", day: 16, title: "Organize o Espaço", description: "Organize um espaço físico (quarto, mesa, armário). Ambiente limpo = clareza mental." },
      { id: "cresc-17", day: 17, title: "Ensinar para Crescer", description: "Ensine algo que sabe a alguém. O ensino é a forma mais poderosa de aprendizado." },
      { id: "cresc-18", day: 18, title: "Descanso Sem Culpa", description: "Descanse de verdade hoje. Sem culpa, sem 'deveria estar produzindo'. O crescimento precisa de pausa." },
      { id: "cresc-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Crescimento. 'O que você está adiando que poderia mudar tudo?'" },
      { id: "cresc-20", day: 20, title: "Consistência > Intensidade", description: "Seu micro-hábito do dia 2 — ainda está fazendo? Se parou, recomece. Sem drama, sem culpa." },
      { id: "cresc-21", day: 21, title: "Crie Algo", description: "Crie: desenho, poema, música, receita, texto. Não precisa ser bom. Precisa ser seu." },
      { id: "cresc-22", day: 22, title: "Conversa Elevadora", description: "Converse com alguém que pensa diferente de você. Não para debater — para aprender." },
      { id: "cresc-23", day: 23, title: "Meditação de Aceitação", description: "'Aqui está bom. E vou avançar.' Aceite onde está AGORA enquanto caminha pra frente." },
      { id: "cresc-24", day: 24, title: "Mentoria Informal", description: "Ajude alguém mais novo ou menos experiente com algo que você já domina." },
      { id: "cresc-25", day: 25, title: "Registre no Diário", description: "Abra o Diário. Liste suas 5 maiores evoluções nos últimos 25 dias. Celebre cada uma." },
      { id: "cresc-26", day: 26, title: "Identidade de Crescimento", description: "'Eu sou alguém que ___.' Complete com 5 frases sobre quem você está se tornando." },
      { id: "cresc-27", day: 27, title: "Compaixão Pelo Processo", description: "'Eu me permito crescer no meu tempo.' O crescimento não é linear — e tudo bem." },
      { id: "cresc-28", day: 28, title: "Próximos Passos", description: "Liste 3 ações concretas para os próximos 30 dias. Pequenas, alcançáveis, suas." },
      { id: "cresc-29", day: 29, title: "Gratidão Pelo Caminho", description: "Agradeça a si mesmo por cada dia completado. Mostrar compromisso JÁ é evolução." },
      { id: "cresc-30", day: 30, title: "Novas Notas", description: "Refaça o Raio-X do dia 1. Compare. Registre no Diário com orgulho." },
    ],
  },
  "solidao": {
    title: "Estar Só, Não Sozinho",
    days: [
      { id: "sol-1", day: 1, title: "Sozinho vs. Solitário", description: "Qual é a diferença entre estar sozinho e estar solitário? Qual você sente mais? Escreva." },
      { id: "sol-2", day: 2, title: "Café Consigo", description: "Tome um café/chá sozinho em silêncio. Sem celular. Observe o mundo ao redor." },
      { id: "sol-3", day: 3, title: "15 Minutos de Nada", description: "Fique 15 minutos sem fazer absolutamente nada. Sem celular, sem TV, sem leitura. Apenas SER." },
      { id: "sol-4", day: 4, title: "Reflita no App", description: "Vá às Perguntas, tema Solidão. Responda 3 perguntas no Diário." },
      { id: "sol-5", day: 5, title: "Passeio Solo", description: "Vá a um lugar novo sozinho: parque, museu, bairro diferente. Sem pressa, sem destino." },
      { id: "sol-6", day: 6, title: "O Que Evito Fazer Só", description: "Restaurante? Cinema? Festa? O que você evita fazer sozinho? Por vergonha de quem?" },
      { id: "sol-7", day: 7, title: "Refeição Sem Tela", description: "Faça uma refeição sozinho sem nenhuma tela. Sinta cada sabor. Seja sua própria companhia." },
      { id: "sol-8", day: 8, title: "Carta de Amor Próprio", description: "Escreva uma carta de amor para si mesmo. Sem ironia, sem vergonha. Com ternura real." },
      { id: "sol-9", day: 9, title: "O Medo do Vazio", description: "O que você teme encontrar quando está a sós com seus pensamentos? Escreva sem filtro." },
      { id: "sol-10", day: 10, title: "Registre no Diário", description: "Abra o Diário. 'A solidão me ensinou...' Complete com 5 coisas." },
      { id: "sol-11", day: 11, title: "Criar Sozinho", description: "Crie algo só — desenhe, escreva, cozinhe, dance. Sem plateia, sem likes. Só prazer." },
      { id: "sol-12", day: 12, title: "Natureza Solo", description: "Passe 20 minutos na natureza sozinho. Árvore, praça, céu. Sem fone de ouvido." },
      { id: "sol-13", day: 13, title: "Abraço Próprio", description: "Abraçe a si mesmo. Braços cruzados sobre o peito. Respire fundo. Diga: 'Estou aqui comigo.'" },
      { id: "sol-14", day: 14, title: "Checkpoint: 2 Semanas", description: "Como está sua relação com a solitude? O que mudou? Registre no Diário." },
      { id: "sol-15", day: 15, title: "Cinema/Filme Solo", description: "Assista um filme sozinho. Sem compartilhar nos stories. Só para você." },
      { id: "sol-16", day: 16, title: "Hobby Resgatado", description: "Resgate 1 hobby que abandonou por 'não ter com quem fazer'. Faça sozinho. Vale." },
      { id: "sol-17", day: 17, title: "Escrita Livre", description: "10 minutos escrevendo sem parar. Sem tema, sem filtro. Puro fluxo de consciência." },
      { id: "sol-18", day: 18, title: "4 Horas Offline", description: "4 horas sem redes sociais. A solidão digital é diferente da solidão real. Sinta a diferença." },
      { id: "sol-19", day: 19, title: "Reflita no App", description: "Vá às Perguntas, tema Solidão. 'A solidão que você sente é real ou é solidão de redes sociais?'" },
      { id: "sol-20", day: 20, title: "Prazer Sem Testemunha", description: "Faça algo prazeroso SÓ para você. Cozinhe, dance, leia. Sem contar para ninguém." },
      { id: "sol-21", day: 21, title: "Jantar Especial Solo", description: "Prepare uma refeição especial para si. Com capricho, com vela se quiser. Você merece." },
      { id: "sol-22", day: 22, title: "Observar o Mundo", description: "Sente em um lugar movimentado sozinho. Observe as pessoas. Invente histórias. Esteja presente." },
      { id: "sol-23", day: 23, title: "Meditação da Lua", description: "À noite, observe o céu. Você está sozinho ali, mas faz parte de algo imenso." },
      { id: "sol-24", day: 24, title: "Solidão Escolhida = Liberdade", description: "Quando você ESCOLHE estar só, o que sente? Compare com quando a solidão te pega de surpresa." },
      { id: "sol-25", day: 25, title: "Registre no Diário", description: "Abra o Diário. Escreva 10 coisas que ama em si mesmo. Sem modéstia. Com verdade." },
      { id: "sol-26", day: 26, title: "Ritual Noturno Solo", description: "Crie um ritual só seu antes de dormir. Chá, leitura, música baixa. Algo sagrado." },
      { id: "sol-27", day: 27, title: "Caminhada de Despedida", description: "Caminhada de 20 minutos como ritual. Cada passo = um obrigado a você por ter chegado até aqui." },
      { id: "sol-28", day: 28, title: "Autocompaixão", description: "'Eu mereço minha própria gentileza. Eu sou digno de amor — inclusive o meu.' Medite com isso." },
      { id: "sol-29", day: 29, title: "Releitura da Jornada", description: "Releia tudo que escreveu. O que o 'você solo' te ensinou?" },
      { id: "sol-30", day: 30, title: "Promessa a Mim", description: "Escreva 1 compromisso consigo mesmo que vai honrar. Registre no Diário. Assine embaixo." },
    ],
  },
};
