export const DEFAULT_REMINDERS = [
  "Deus Pai conhece cada pensamento teu. Entrega-Lhe as tuas preocupações hoje.",
  "A Sua graça é suficiente para este dia. Confia nEle.",
  "Mesmo nos momentos de silêncio, Deus Pai está presente e a trabalhar.",
  "Busca primeiro o reino de Deus e o resto será acrescentado.",
  "A oração não muda Deus — muda o coração de quem ora.",
  "Não caminha sozinho. O Pai caminha contigo a cada passo.",
  "A fé cresce quando é exercitada. Confie hoje naquilo que ainda não vê.",
  "O amor de Deus Pai por ti não depende do que fizeste — é incondicional.",
  "Cada amanhecer é uma nova misericórdia do Pai Celeste.",
  "O Senhor é o teu pastor. Não te faltará nada.",
  "Nas tuas fraquezas, a força de Deus se manifesta.",
  "Descansa no Pai. Ele carrega o peso que tu não consegues.",
  "A paz de Deus ultrapassa todo o entendimento. Recebe-a hoje.",
  "Agradecer a Deus Pai é a forma mais profunda de reconhecer a Sua presença.",
  "A tua vida tem propósito — e esse propósito vem do coração do Pai.",
  "Nenhum momento vivido com Deus é tempo perdido.",
  "A Palavra de Deus é lâmpada para o teu caminho. Ilumina o passo seguinte.",
  "Quando a tempestade vier, lembra: o Pai está contigo no barco.",
  "Perfeição não é o que Deus pede — pede um coração disponível.",
  "Cresce na intimidade com Deus Pai. Ela transforma tudo.",
  "Os planos do Pai para a tua vida são de paz e não de mal.",
  "Não te apresses. O tempo de Deus é sempre perfeito.",
  "O Pai te conhece pelo nome. Não és apenas mais um.",
  "Ser filho de Deus não é um título — é uma identidade que transforma.",
  "O perdão do Pai é mais profundo do que qualquer erro teu.",
  "Hoje, leva a presença de Deus para cada conversa e decisão.",
  "A gratidão abre os olhos para as bênçãos que já existem.",
  "Deus Pai nunca desiste de ti — nem nos dias em que tu desistes de ti mesmo.",
  "Cada oração é um passo em direção ao coração do Pai.",
  "A tua identidade está em Cristo, não nas circunstâncias.",
  "Confiar em Deus é também um ato de humildade.",
  "O que parece um desvio, nas mãos do Pai, é sempre um propósito.",
  "Não compares a tua jornada com a de outro. O Pai tem um caminho único para ti.",
  "A adoração não muda as circunstâncias — muda a perspetiva.",
  "Hoje, escolhe olhar o que Deus Pai fez, e não o que ainda não resolveu.",
  "A misericórdia do Pai é renovada a cada manhã. Recomeça com Ele.",
  "Busca o rosto de Deus Pai — não apenas as Suas bênçãos.",
  "A Sua fidelidade é maior do que qualquer problema que enfrentas.",
  "A oração é o pulmão da alma. Respira com Deus hoje.",
  "Pequenos momentos de silêncio com Deus são sementes de grandes transformações.",
  "O Pai vê o que ninguém mais vê — incluindo o teu esforço silencioso.",
  "Mesmo quando não sentes a presença de Deus, a fé garante que Ele está.",
  "A Sua voz fala em voz baixa. Aprende a ouvir no silêncio.",
  "Ser humilde diante do Pai é o início de toda a sabedoria.",
  "Nenhuma lágrima derramada diante de Deus é desperdiçada.",
  "O Pai celebra cada passo de fé, por menor que pareça.",
  "A tua oração de hoje pode mudar o amanhã de alguém.",
  "Deus Pai é bom — mesmo quando a vida não parece boa.",
  "Não te cansas de procurar a Deus. Ele nunca se cansa de encontrar-te.",
  "A Sua presença é o maior presente que podes ter neste dia.",
  "Meditar na Palavra de Deus renova a mente e aquieta o coração.",
  "O Pai é um Deus de detalhes. Nada na tua vida passa despercebido.",
  "A fé não elimina as dificuldades — mas garante que não passas por elas sozinho.",
  "Escolhe hoje ser instrumento do amor de Deus Pai para alguém.",
  "A tua história ainda está a ser escrita pelo maior Autor.",
  "Com Deus, o impossível tem outro nome: milagre em preparação.",
  "Cada versículo memorizado é uma semente plantada no coração.",
  "A presença de Deus Pai transforma o comum em sagrado.",
  "Não precisas de ter tudo resolvido para orar. Ora com o que tens.",
  "A esperança em Deus Pai nunca decepciona.",
  "O teu clamor chega ao coração do Pai antes de sair dos teus lábios.",
  "Confia no Senhor de todo o teu coração, e não te apoies no teu próprio entendimento.",
  "Hoje é um novo encontro com Deus Pai. Apresenta-te.",
];

export const THEMED_REMINDERS: Record<string, string[]> = {
  ansiedade: [
    "Lança sobre Deus Pai toda a tua ansiedade, porque Ele tem cuidado de ti.",
    "A paz que Deus dá ultrapassa toda a compreensão. Pede-a hoje.",
    "Quando o coração treme, lembra: o Pai está no controlo."
  ],
  identidade: [
    "A tua identidade não está no que fazes, mas em quem o Pai diz que és.",
    "Foste criado à imagem de Deus. Isso não muda com as circunstâncias.",
    "Ser filho de Deus Pai é a identidade mais profunda que podes ter."
  ],
  solidão: [
    "Mesmo no silêncio mais profundo, o Pai diz: estou aqui.",
    "A solidão pode ser o espaço onde o Pai mais fala. Escuta.",
    "Nunca estás verdadeiramente sozinho quando tens o Pai contigo."
  ],
  propósito: [
    "O Pai planeou o teu propósito antes de te criar. Busca-O para descobrires.",
    "Cada dom que tens foi dado pelo Pai para servir e amar.",
    "O teu propósito não é acidental — foi tecido pelo coração de Deus."
  ],
  crescimento: [
    "O crescimento espiritual acontece em cada escolha de confiar no Pai.",
    "Deus Pai usa cada estação da vida para te formar à imagem de Cristo.",
    "Ser transformado é o maior crescimento — e começa no encontro com o Pai."
  ]
};
